apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aptly.fullname" . }}-public
  labels:
    {{- include "aptly.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aptly.selectorLabels" . | nindent 6 }}
      component: public
  template:
    metadata:
      labels:
        {{- include "aptly.labels" . | nindent 8 }}
        component: public
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html
              subPath: public
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "aptly.fullname" . }}-data
