apiVersion: v1
kind: Service
metadata:
  name: {{ include "aptly.fullname" . }}-api
  labels:
    {{- include "aptly.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.type }}
  ports:
    - port: {{ .Values.apiService.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "aptly.selectorLabels" . | nindent 4 }}
    component: api
